export const NEUTRAL_NPC_QUOTES = [
  `"I used to be an adventurer like you, then I took an arrow to the knee. Now I sell arrows."`,
  `"The dungeon master said this room was optional. He was lying. They always lie."`,
  `"My cart is stuck. Has been for three weeks. I've made peace with it."`,
  `"Don't touch the second door on the left. Nobody will tell you why. Don't ask."`,
  `"I'm not lost. The dungeon is lost. I'm exactly where I meant to be."`,
  `"Technically I'm still on the clock from my last job. That was six years ago."`,
  `"The goblin king offered me a very competitive benefits package. I'm considering it."`,
  `"I found a magic sword once. Traded it for a sandwich. No regrets. Good sandwich."`,
  `"This torch has been burning for forty years. I stopped asking questions."`,
  `"Yes, I live here. No, I don't pay rent. The dungeon hasn't asked."`,
  `"The prophecy said a chosen one would pass through here. You don't look like it but I've been wrong before."`,
  `"I've mapped every inch of this dungeon. Lost the map. Started over. Lost that one too."`,
  `"My familiar left me for a warlock with better snacks. I understand. The snacks were incredible."`,
  `"The last party that came through said they'd be back in ten minutes. That was four years ago."`,
  `"I'm a professional trap tester. It pays poorly. It pays at all, which is something."`,
  `"Dragons aren't so bad once you get to know them. The trick is surviving the getting-to-know-them part."`,
  `"I have seventeen magic items. None of them do anything useful. One of them hums."`,
  `"The dungeon has a complaints department. I filed something in 1987. Still waiting."`,
  `"Yes, I'm a skeleton. No, I'm not hostile. I'm off the clock. Union rules."`,
  `"I've been trying to open this door for eleven years. We've come to an understanding."`,
  `"The mimic ate my lunch. We don't talk about it."`,
  `"I'm not a ghost. I'm just very pale and I pass through walls sometimes. Completely different."`,
  `"The wizard who made this place had a great sense of humor. Present tense. He's still here somewhere."`,
  `"I sell maps to the treasure. The treasure is the friends we made along the way. That'll be 50 gold."`,
  `"My philosophy is simple: if you can outrun it, it's not your problem. I am very fast."`,
  `"The dungeon ecosystem is actually quite delicate. Please stop killing everything."`,
  `"I was sent here by the thieves guild. I've forgotten what for. It's been a while."`,
  `"The last adventurer who came through said 'I'll be right back.' Classic mistake."`,
  `"I am absolutely definitely not a dragon in a very convincing disguise. Good day."`,
  `"The answer to the riddle is 'time.' It's always time. You're welcome."`,
]

export const MERCHANT_STOCK_COUNT = 6
export const MERCHANT_MARKUP = 1.15