export const CLASS_HP_DIE: Record<string, number> = {
  alchemist: 8,
  artificer: 6,
  barbarian: 12,
  bard: 6,
  cleric: 8,
  druid: 8,
  favored_soul: 8,
  fighter: 10,
  monk: 8,
  paladin: 10,
  ranger: 10,
  rogue: 6,
  sorcerer: 4,
  warlock: 6,
  wizard: 4,
  sacred_fist: 10,
  dark_apostate: 8,
  stormsinger: 6,
  blightcaster: 8,
  acolyte_of_the_skin: 6,
  dark_hunter: 10,
  dragon_lord: 10,
  wild_mage: 4,
  dragon_disciple: 8,
  arcane_trickster: 6,
}

export const rollHp = (die: number) => Math.floor(Math.random() * die) + 1